Enhancement thread get current
nanvix/microkernel pull request #285
Opened 2020-09-23 22:05 UTC by Nicolas-Vanz

I added a function to get the current thread id.

Closes #282

2020-09-24 13:00 UTC, joaovicentesouto requested changes
Very good @Nicolas-Vanz 

There were only a few points in the code to improve and some places were missing for you to replace in this file: `src/kernel/sys/thread.c`

To find them, you can use the [Find and Replace](https://flight-manual.atom.io/using-atom/sections/find-and-replace/#:~:text=To%20search%20within%20your%20current,the%20matches%20in%20that%20file.) functionality of the Atom Editor or use the `grep` command (`grep -r "thread_get_id(thread_get_curr())" .`)

You can edit, commit, and push these changes. After that, I will explain how we can put all those changes together into one commit without copy/paste.

2020-09-25 21:19 UTC, ppenna approved these changes

2020-09-25 21:20 UTC, ppenna commented
@joaovicentesouto is it ok now?

2020-09-26 12:46 UTC, joaovicentesouto approved these changes
Approved, great work @Nicolas-Vanz

2020-09-26 15:19 UTC, merged