[pm] Enhancement: Thread return value
nanvix/microkernel pull request #288
Opened 2020-10-02 16:27 UTC by hansb21

In this PR, I implemented the possibility for using the return values of threads both in single-thread and multi-threaded. 

This PR closes #254

2020-10-02 16:52 UTC, joaovicentesouto requested changes
There are still some compilation bugs in MPPA, check and request for our review again @hansb21 .

2020-10-05 13:09 UTC, joaovicentesouto requested changes
Congratulations @hansb21 , that's right.
Just improve some things and we close this issue.

2020-10-05 13:09 UTC, joaovicentesouto commented on src/kernel/pm/singlethread.c
> +		if ((ret == 0) && (retval != NULL))
- Add a comment to explain what are you doing here.
- Add again the `mm_is_uaddr((vaddr_t) retval)` check to the `if`.

2020-10-05 13:09 UTC, joaovicentesouto commented on src/kernel/pm/singlethread.c
> +		       	*retval = NULL;
Replace spaces to tabs.

2020-10-05 13:09 UTC, joaovicentesouto commented on src/kernel/pm/singlethread.c
> +			} 	}
Fix scope indentation. Two `}` in the same lines.

2020-10-05 13:09 UTC, joaovicentesouto commented on src/kernel/pm/multithread.c
> +			}
Remove one tab from 574 to 578 lines.

2020-10-05 13:09 UTC, joaovicentesouto commented on src/kernel/pm/multithread.c
> +		if ((ret == 0) && (retval != NULL))
- Add a comment to explain what are you doing here.
- Add again the `mm_is_uaddr((vaddr_t) retval)` check to the `if`.

2020-10-06 00:25 UTC, ppenna requested changes
@joaovicentesouto please double check this with @hansb21

2020-10-06 00:25 UTC, ppenna commented on src/kernel/pm/multithread.c
> +		   	*retval = NULL;
why this?

2020-10-06 00:25 UTC, ppenna commented on src/kernel/pm/singlethread.c
> +#define KTHREAD_EXIT_VALUE_NUM (3 * KTHREAD_MAX)
3 seems a magic number. Can we have a #define for it?

2020-10-06 00:25 UTC, ppenna commented on src/kernel/pm/singlethread.c
> +		}
This code is replicated. Couldn't we have a private routine for it?

2020-10-26 20:35 UTC, joaovicentesouto requested changes
We're almost there, just fix a few points about code style.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/makefile
> +      $(wildcard pm/thread/*.c)  \
Align all `\` using `spaces`, not `tabs`.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +PUBLIC void thread_save_retval(void* retval, struct thread *curr)
2 points here:
- Missing documentation.
- May be `curr` is not a good name because suggests that we saving the return value of the current thread but we this is not necessary. You can change it to `t` or `leaving_thread`.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +			exitvalue_counter = (exitvalue_counter + 1) % KTHREAD_EXIT_VALUE_NUM;
There is an additional `tab` here. Remove and leave aligned with the first line that is correct.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +}
All indentation of this function is wrong. There is mixing `tab` and `spaces`, and are several extra indentations.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +PUBLIC void thread_search_retval(void **retval, int tid)
Add documentation.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.h
> +    EXTERN void thread_save_retval(void* retval, struct thread *curr);
Add documentation (look at the comment on .c)

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/multithread.c
> +#include <nanvix/kernel/mm.h>
Move this include to before of the thread.h include.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/multithread.c
> +	thread_save_retval(retval, curr);
Insert an extra `tab` here. We add indentation inside of a critical region to make that explicitly, i.e., between lock/unlock.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/multithread.c
> +		 * are valid
Update this comment. We do not check the retval here.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/singlethread.c
> +#include <nanvix/kernel/mm.h>
Move this include to before of the thread.h

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/singlethread.c
> +		cond_broadcast(&joincond[mycoreid]);
Insert a `tab` in lines 214, 216, and 217 because it is a critical region.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/singlethread.c
> +
Remove this line.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/singlethread.c
> +		 */
Update this comment.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +	if (retval)
Comments on what are you doing here.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +	if (retval != NULL)
Comments on what are you doing here.

2020-10-26 20:35 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +    	for (int i = 0; i < KTHREAD_EXIT_VALUE_NUM; i++)
Comments on what are you doing here.

2020-10-28 00:15 UTC, ppenna requested changes
@hansb21 could you apply the changes requested by @joaovicentesouto ?

2020-10-28 16:39 UTC, joaovicentesouto requested changes
There are still some points for improvement.

I also checked a new one which is to move the definition from `KTHREAD_EXIT_VALUE_NUM` to the thread.h

2020-10-28 16:39 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +    	exit_values[exitvalue_counter].tid = thread_get_id(leaving_thread);
Use `tab` here to indentation.

2020-10-28 16:39 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +/**
Always put a new line between the end of a function and the beginning of the documentation.

2020-10-28 16:39 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +}
This function still with the wrong indentation.

2020-10-28 16:39 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.h
> +    EXTERN void thread_save_retval(void* retval, struct thread *curr);
Still missing documentation.

2020-10-28 16:39 UTC, joaovicentesouto commented on src/kernel/pm/thread/singlethread.c
> +
Still need to remove

2020-10-28 16:39 UTC, joaovicentesouto commented on src/kernel/pm/thread/common.c
> +#define KTHREAD_EXIT_VALUE_NUM (3 * KTHREAD_MAX)
Move the definition of `KTHREAD_EXIT_VALUE_NUM` to thread.h

2020-10-28 17:32 UTC, hansb21 commented on src/kernel/pm/thread/common.c
> +#define KTHREAD_EXIT_VALUE_NUM (3 * KTHREAD_MAX)
fixed.

2020-10-28 17:32 UTC, hansb21 commented on src/kernel/pm/thread/common.c
> +/**
fixed.

2020-10-28 21:07 UTC, ppenna requested changes
Thanks @hansb21 =D

Could you fix the changes that are left?

2020-10-29 13:26 UTC, joaovicentesouto approved these changes
Approved.

2020-10-29 14:18 UTC, joaovicentesouto requested changes
Libnanvix is broken on unix in the `RELEASE=false` mode. We must verify why.

2020-10-29 14:42 UTC, joaovicentesouto approved these changes
Bug on unix fixed.
Approved.

2020-11-24 23:07 UTC, ppenna approved these changes

2020-11-24 23:07 UTC, merged