[pm] Enhancement: Dynamically allocate user/kernel stack of a thread …
nanvix/microkernel pull request #290
Opened 2020-10-28 18:28 UTC by Nicolas-Vanz

I made threads to be dynamically allocated in memory. A new thread state was also added: the THREAD_ZOMBIE, that indicates that the thread can be released by another thread.

Closes #283

2020-10-28 21:02 UTC, ppenna requested changes

2020-10-28 21:02 UTC, ppenna commented on src/kernel/pm/multithread.c
> +
@joaovicentesouto shouldn't this be in a critical region? We are querying the state of a thread, which can be changed elsewhere....

2020-10-29 11:37 UTC, joaovicentesouto commented on src/kernel/pm/multithread.c
> +
You are right, this should be protected.

2020-10-29 11:45 UTC, joaovicentesouto requested changes
That is nice work. Only missed an important point that is to update the `contrib/hal` to the version with the increased kpool.

2020-10-29 11:45 UTC, joaovicentesouto commented on src/kernel/pm/multithread.c
> +			thread_free(curr->next);
To prevent of introduce an undefined behavior, we should set the `curr->next` to `NULL`.

2020-10-29 11:45 UTC, joaovicentesouto commented on src/kernel/pm/multithread.c
> +		thread_free(curr_thread->next);
To prevent of introduce an undefined behavior, we should set the `curr->next` to `NULL`.

2020-10-29 11:48 UTC, joaovicentesouto commented on src/kernel/pm/multithread.c
> +			thread_free(curr->next);
We must verify if the `curr->next` is valid.

2020-10-29 12:39 UTC, joaovicentesouto approved these changes
Approved.

2020-11-24 22:00 UTC, ppenna approved these changes

2020-11-24 22:34 UTC, merged